// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTie93c5UboVlkGKt_P9cv5aNpPpZzASc',
    appId: '1:500698306726:web:a352fe276759740da17c67',
    messagingSenderId: '500698306726',
    projectId: 'fir-a0c2c',
    authDomain: 'fir-a0c2c.firebaseapp.com',
    storageBucket: 'fir-a0c2c.firebasestorage.app',
    measurementId: 'G-8MBD2VC8CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJBqJOngsBYPx228rGsdKpzdUKCS-tNWg',
    appId: '1:500698306726:android:836cfa3caaab59c8a17c67',
    messagingSenderId: '500698306726',
    projectId: 'fir-a0c2c',
    storageBucket: 'fir-a0c2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANsN0OrZMahbCn3KWIQ-EYRK6vk1nyqvg',
    appId: '1:500698306726:ios:613329d46154f796a17c67',
    messagingSenderId: '500698306726',
    projectId: 'fir-a0c2c',
    storageBucket: 'fir-a0c2c.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANsN0OrZMahbCn3KWIQ-EYRK6vk1nyqvg',
    appId: '1:500698306726:ios:613329d46154f796a17c67',
    messagingSenderId: '500698306726',
    projectId: 'fir-a0c2c',
    storageBucket: 'fir-a0c2c.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );
}
